In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error, r2_score

In [2]:
df = pd.read_csv('Data/train.csv')

In [3]:
df.head()

      x          y
0  24.0  21.549452
1  50.0  47.464463
2  15.0  17.218656
3  38.0  36.586398
4  87.0  87.288984

In [4]:
df.isnull().sum()

x    0
y    1
dtype: int64

In [5]:
df.dropna(subset=['x', 'y'], inplace=True)

In [6]:
df.isnull().sum()

x    0
y    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

x = df['x']
y = df['y']

x_scaled = scaler_x.fit_transform(np.array(x).reshape(-1, 1))
y_scaled = scaler_y.fit_transform(np.array(y).reshape(-1, 1))

In [9]:
regression = LinearRegression()

model = regression.fit(x_scaled, y_scaled)

In [10]:
test_df = pd.read_csv('Data/test.csv')

In [11]:
test_df.head()

    x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [12]:
x_test = test_df['x']
y_test = test_df['y']

x_test_scaled = scaler_x.fit_transform(np.array(x_test).reshape(-1, 1))

In [13]:
y_pred = model.predict(x_test_scaled)

In [14]:
y_pred_inversed = scaler_y.inverse_transform(y_pred)

In [15]:
print(mean_absolute_error(y_test, y_pred_inversed))
print(mean_squared_error(y_test, y_pred_inversed))
print(mean_absolute_percentage_error(y_test, y_pred_inversed) * 100)
print(r2_score(y_test, y_pred_inversed))

2.41577185004126
9.43292219203933
13.545963035353854
0.9888014444327563